// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto a = 0;
    auto b = 1;
    std::cout << a;
    std::cout << b;
    // Generated example file - Python for loop statement implementation
    return 0;
}

