// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto fib(auto n) {
    if (n <= 1) {
        return n;
    }
    return fib(n - 1) + fib(n - 2);
}

int main() {
    std::cout << fib(5) << std::endl;
    std::cout << fib(6) << std::endl;
    std::cout << fib(7) << std::endl;
    return 0;
}
