// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyComparison [OpLe] [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "n")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 1)}]
auto fib(auto n) {
    if (0) {
    return n;
}
    return fib(n - 1) + fib(n - 2);
}

int main() {
    std::cout << fib(5);
    std::cout << fib(6);
    std::cout << fib(7);
    return 0;
}

