// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto fib(auto n) {
    if (n <= 1) {
        return n;
    }
    auto a = 0;
    auto b = 1;
    auto i = 2;
    while (i <= n) {
        auto c = a + b;
        a = b;
        b = c;
        i = i + 1;
    }
    return b;
}

int main() {
    std::cout << fib(5) << std::endl;
    std::cout << fib(6) << std::endl;
    std::cout << fib(7) << std::endl;
    std::cout << fib(8) << std::endl;
    std::cout << fib(9) << std::endl;
    std::cout << fib(10) << std::endl;
    return 0;
}
