// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto a = 1;
    auto b = 1;
    auto c = a + b;
    auto d = b + c;
    auto e = c + d;
    std::cout << a;
    std::cout << b;
    std::cout << c;
    std::cout << d;
    std::cout << e;
    return 0;
}

