// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto a = 1;
    auto b = 1;
    std::cout << a << std::endl;
    std::cout << b << std::endl;
    auto next_fib = a + b;
    std::cout << next_fib << std::endl;
    auto a = b;
    auto b = next_fib;
    auto next_fib = a + b;
    std::cout << next_fib << std::endl;
    return 0;
}

