// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto num1 = 15;
    auto num2 = 25;
    auto sum_result = num1 + num2;
    auto diff_result = num2 - num1;
    auto mult_result = num1 * 2;
    std::cout << sum_result;
    std::cout << diff_result;
    std::cout << mult_result;
    return 0;
}

