// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << 5 << std::endl;
    std::cout << 8 << std::endl;
    std::cout << 13 << std::endl;
    return 0;
}

