// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto add(auto a, auto b) {
    return a + b;
}

int main() {
    auto x = 5;
    auto y = 3;
    auto result = add(x, y);
    std::cout << result << std::endl;
    return 0;
}

