// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto base = 5;
    auto doubled = base * 2;
    auto final = doubled + 10;
    std::cout << base;
    std::cout << doubled;
    std::cout << final;
    return 0;
}

