// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello from Python!";
    std::cout << "Simple calculation:";
    auto result = 5 + 3;
    std::cout("5 + 3 =", result);
    return 0;
}

