// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 14 declarations
// Generating function: testBasic
void testBasic() {
    int x = 10;
    int y = 20;
    auto result = x + y;
    std::cout << " = " << result << " + " << y << "Basic arithmetic: " << x << std::endl;
}

// Generating function: testSimpleIf
void testSimpleIf() {
    int x = 15;
    if (x > 10) {
    {
    std::cout << "x is greater than 10" << std::endl;
}
} else {
    {
    std::cout << "x is not greater than 10" << std::endl;
}
}
}

// Generating function: testSimpleFor
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLt (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoInt 5)})}
void testSimpleFor() {
    std::cout << "Counting: ";
    for (int i = 0; i < 5; ++i) {
    std::cout << i << " ";
}
    std::cout << "" << std::endl;
}

// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: testFunctionCalls
void testFunctionCalls() {
    auto result = add(5, 7);
    std::cout << "Function call result: " << result << std::endl;
}

// Generating function: testStrings
void testStrings() {
    std::string name = "Go";
    auto greeting = "Hello, " + name;
    std::cout << "String concatenation: %s" << std::endl;
}

// Generating function: testVariableDeclarations
void testVariableDeclarations() {
    int a = 10;
    auto b = 20;
    int c = 30;
    std::cout << ", c=" << c << ", b=" << b << "Variables: a=" << a << std::endl;
}

// Generating function: testBooleans
void testBooleans() {
    bool x = true;
    bool y = false;
    std::cout << "Boolean operations: %t && %t = %t\n" << std::endl;
    std::cout << "Boolean operations: %t || %t = %t\n" << std::endl;
}

// Generating function: testSimpleArray
// TODO: Implement Go expression: GoIndex (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "numbers")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoInt 0)})
void testSimpleArray() {
    auto numbers = {1, 2, 3};
    std::cout << "Array: %v" << std::endl;
    std::cout << "First element: " << 0 << std::endl;
}

// Generating function: divideSimple
std::tuple<int, int> divideSimple(int a, int b) {
    return std::make_tuple(a / b, a % b);
}

// Generating function: testMultiReturn
void testMultiReturn() {
    auto quotient = divideSimple(10, 3);
    std::cout << " remainder " << remainder << "10 / 3 = " << quotient << std::endl;
}

// Generating function: fibonacciSimple
int fibonacciSimple(int n) {
    if (n <= 1) {
    {
    return n;
}
}
    return fibonacciSimple(n - 1) + fibonacciSimple(n - 2);
}

// Generating function: testRecursion
void testRecursion() {
    auto result = fibonacciSimple(6);
    std::cout << "Fibonacci(6) = " << result << std::endl;
}

// Generating function: main
int main() {
    std::cout << "=== 基础Go特性测试 ===" << std::endl;
    testBasic();
    testSimpleIf();
    testSimpleFor();
    testFunctionCalls();
    testStrings();
    testVariableDeclarations();
    testBooleans();
    testSimpleArray();
    testMultiReturn();
    testRecursion();
    std::cout << "=== 基础测试完成 ===" << std::endl;
    return 0;
}

