// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 13 declarations
// Generating function: testBasicTypes
void testBasicTypes() {
    int intVar = 42;
    int shortInt = 10;
    double floatVar = 3.14;
    double shortFloat = 2.71;
    std::string stringVar = "hello";
    std::string shortString = "world";
    bool boolVar = true;
    bool shortBool = false;
    std::cout << "=== 基础类型测试 ===" << std::endl;
    std::cout << "整数: " << intVar << ", " << shortInt << std::endl;
    std::cout << "浮点数: " << floatVar << ", " << shortFloat << std::endl;
    std::cout << "字符串: " << stringVar << ", " << shortString << std::endl;
    std::cout << "布尔值: " << std::boolalpha << boolVar << ", " << std::boolalpha << shortBool << std::endl;
}

// Generating function: testArithmetic
void testArithmetic() {
    int a = 15;
    int b = 7;
    std::cout << "=== 算术运算测试 ===" << std::endl;
    std::cout << a << " + " << b << " = " << a + b << std::endl;
    std::cout << a << " - " << b << " = " << a - b << std::endl;
    std::cout << a << " * " << b << " = " << a * b << std::endl;
    std::cout << a << " / " << b << " = " << a / b << std::endl;
    std::cout << a << " %% " << b << " = " << a % b << std::endl;
}

// Generating function: testControlFlow
void testControlFlow() {
    int x = 25;
    std::cout << "=== 控制流测试 ===" << std::endl;
    if (x > 30) {
    {
    std::cout << x << " is greater than 30" << std::endl;
}
} else {
    if (x > 20) {
    {
    std::cout << x << " is greater than 20 but not greater than 30" << std::endl;
}
} else {
    {
    std::cout << x << " is 20 or less" << std::endl;
}
}
}
}

// Generating function: testLoops
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLt (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoInt 5)})}
void testLoops() {
    std::cout << "=== 循环测试 ===" << std::endl;
    std::cout << "for loop: ";
    for (int i = 0; i < 5; ++i) {
    std::cout << i << " ";
}
    std::cout << "" << std::endl;
}

// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: multiply
int multiply(int x, int y) {
    return x * y;
}

// Generating function: testFunctions
void testFunctions() {
    std::cout << "=== 函数测试 ===" << std::endl;
    auto result1 = add(8, 12);
    auto result2 = multiply(6, 7);
    std::cout << "add(8, 12) = " << result1 << std::endl;
    std::cout << "multiply(6, 7) = " << result2 << std::endl;
}

// Generating function: testPrintln
void testPrintln() {
    std::cout << "=== Printf/Println测试 ===" << std::endl;
    std::cout << "多参数println:" << " " << 100 << " " << 200 << " " << 300 << std::endl;
    std::cout << "字符串和数字:" << " " << "result" << " " << 42 << std::endl;
    std::cout << "混合类型:" << " " << "answer" << " " << 42 << " " << true << std::endl;
    std::string name = "测试";
    int age = 25;
    double score = 95.5;
    std::cout << "Printf测试: " << name << "年龄" << age << "岁，得分" << std::fixed << std::setprecision(1) << score << std::endl;
}

// Generating function: factorial
int factorial(int n) {
    if (n <= 1) {
    {
    return 1;
}
}
    return n * factorial(n - 1);
}

// Generating function: fibonacciSimple
int fibonacciSimple(int n) {
    if (n <= 1) {
    {
    return n;
}
}
    return fibonacciSimple(n - 1) + fibonacciSimple(n - 2);
}

// Generating function: testRecursion
void testRecursion() {
    std::cout << "=== 递归测试 ===" << std::endl;
    auto fact5 = factorial(5);
    auto fib7 = fibonacciSimple(7);
    std::cout << "factorial(5) = " << fact5 << std::endl;
    std::cout << "fibonacci(7) = " << fib7 << std::endl;
}

// Generating function: testComplexExpressions
void testComplexExpressions() {
    std::cout << "=== 复杂表达式测试 ===" << std::endl;
    int a = 10;
    int b = 5;
    int c = 3;
    auto result = a + b * c - a / b;
    std::cout << "((10 + 5) * 3) - (10 / 5) = " << result << std::endl;
    auto condition = a > b && b > c;
    std::cout << "(10 > 5) && (5 > 3) = %t" << std::endl;
}

// Generating function: main
int main() {
    std::cout << "====== Go编译器回归测试套件 ======\\n" << std::endl;
    testBasicTypes();
    std::cout << "" << std::endl;
    testArithmetic();
    std::cout << "" << std::endl;
    testControlFlow();
    std::cout << "" << std::endl;
    testLoops();
    std::cout << "" << std::endl;
    testFunctions();
    std::cout << "" << std::endl;
    testPrintln();
    std::cout << "" << std::endl;
    testRecursion();
    std::cout << "" << std::endl;
    testComplexExpressions();
    std::cout << "" << std::endl;
    std::cout << "====== 所有回归测试完成 ======" << std::endl;
    return 0;
}

