// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <vector>
#include <sstream>
#include <string>
#include <iostream>

// DEBUG: Processing f-string template: x = {x}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: Processing f-string template: y = {y}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: Processing f-string template: x + y = {x + y}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: PyComparison ops=[OpGt] exprs=[Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "x")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "y")}]
// DEBUG: Single comparison OpGt -> >
// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
// IF condition: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyComparison [OpGt] [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "x")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "y")}]}
// DEBUG: Processing f-string template: Numbers: {numbers}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: Processing f-string template: First number: {numbers[0]}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
int main() {
    auto x = 10;
    auto y = 20;
    std::cout << "x = " << x << std::endl;
    std::cout << "y = " << y << std::endl;
    std::cout << "x + y = " << x + y << std::endl;
    if (x > y) {
    std::cout << "x is greater than y" << std::endl;
} else {
    std::cout << "y is greater than or equal to x" << std::endl;
}
    auto numbers = std::vector<int>{1, 2, 3, 4, 5};
    std::cout << "Numbers: " << numbers << std::endl;
    std::cout << "First number: " << numbers[0] << std::endl;
    return 0;
}

