// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

auto simple_func(auto x) {
    return x;
}

// DEBUG: Fallback case for function: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "simple_func")}
// DEBUG: Generating print with 1 arguments
void test() {
    auto result = simple_func(5);
    std::cout << result << std::endl;
}

// DEBUG: Fallback case for function: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "test")}
int main() {
    test();
    return 0;
}

