// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <sstream>
#include <string>
#include <iostream>

// DEBUG: Processing f-string template: x + y = {x + y}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: Processing f-string template: x * y = {x * y}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
int main() {
    auto x = 10;
    auto y = 5;
    std::cout << "x + y = " << x + y << std::endl;
    std::cout << "x * y = " << x * y << std::endl;
    return 0;
}

