// Generated by HyperStatic/CXX Compiler
#include <chrono>
#include <tuple>
#include <memory>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <vector>
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}

