// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

auto add(auto a, auto b) {
    return a + b;
}

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_add = 42;

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_print = 42;

// TODO: Render other declaration types

int main() {
    std::cout << add(std::make_tuple(1, 2)) << std::endl;
    return 0;
}

