// Generated by HyperStatic/CXX Compiler
/* Original Source (./debug_memory_test.py):
result = 0
i = 0
while i < 1000000:
    result = result + (i % 1000)
    i = i + 1
print(f"Processed {result} elements")
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

// While loop converted to comment

// Expression statement: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyCall (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "print")}) [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyFString [FStringExpr {fstrExpr = Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "result")}, fstrConversion = Nothing, fstrFormatSpec = Nothing}]})}]}

}
using namespace fluxus;

int main() {
    auto result = 0;
    auto i = 0;
    while (i < 1000000) {
    result = result + i % 1000;
    i = i + 1;

}
    std::cout << 0 << "\n";
    return 0;
}

