// Generated by HyperStatic/CXX Compiler
/* Original Source (./debug_test.py):
def add(a, b):
    return a + b
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

auto add(auto a, auto b) {
    return a + b;
}

}

int main() {
    return 0;
}

}
