{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}
import Fluxus.CodeGen.CPP
import Fluxus.AST.Common
import Fluxus.AST.Python
import Data.Text (Text)
import Data.List (intercalate)

-- Create a simple Python AST for testing
testAST :: PythonAST
testAST = PythonAST $ PythonModule
  { pyModuleName = Nothing
  , pyModuleDoc = Nothing
  , pyModuleImports = []
  , pyModuleBody = 
      [ Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
          PyFuncDef $ PythonFuncDef
            { pyFuncName = Identifier "add"
            , pyFuncDecorators = []
            , pyFuncParams = 
                [ Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
                    ParamNormal (Identifier "x") Nothing Nothing
                , Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
                    ParamNormal (Identifier "y") Nothing Nothing
                ]
            , pyFuncReturns = Nothing
            , pyFuncBody = 
                [ Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
                    PyReturn $ Just $ 
                      Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
                        PyBinaryOp OpAdd
                          (Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ PyVar $ Identifier "x")
                          (Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ PyVar $ Identifier "y")
                ]
            , pyFuncDoc = Nothing
            , pyFuncIsAsync = False
            }
      , Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
          PyAssign 
            [ Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                PatVar $ Identifier "result"
            ]
            (Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $
              PyCall 
                (Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                  PyVar $ Identifier "add")
                [ Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                    ArgPositional $ 
                      Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                        PyLiteral $ PyInt 1
                , Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                    ArgPositional $ 
                      Located (SourceSpan "test.py" (SourcePos 0 0) (SourcePos 0 0)) $ 
                        PyLiteral $ PyInt 2
                ]
            )
      ]
  }

main :: IO ()
main = do
  putStrLn "Testing C++ code generation..."
  let config = CppGenConfig
        { cgcOptimizationLevel = 2
        , cgcEnableInterop = True
        , cgcTargetCppStd = "c++20"
        , cgcUseSmartPointers = True
        , cgcEnableParallel = True
        , cgcEnableCoroutines = True
        , cgcNamespace = "hyperstatic"
        , cgcHeaderGuard = "HYPERSTATIC_GENERATED"
        }
  let cppUnit = generateCppMain config (Left testAST)
  putStrLn $ "Generated C++ code:"
  putStrLn $ showCppUnit cppUnit

showCppUnit :: CppUnit -> String
showCppUnit (CppUnit includes _ decls) = 
  let renderedCode = unlines $
        [ "// Generated by HyperStatic/CXX Compiler - DEBUG VERSION" ] ++
        map (\inc -> "#include " ++ inc) includes ++
        [ "" ] ++
        map showCppDecl decls
  in renderedCode

showCppDecl :: CppDecl -> String
showCppDecl = \case
  CppFunction name retType params body -> 
    showCppType retType ++ " " ++ name ++ "(" ++ 
    intercalate ", " (map showCppParam params) ++ ") {\n" ++
    unlines (map ("    " ++) (map showCppStmt body)) ++
    "}\n"
  CppVariable name varType Nothing -> 
    case varType of
      CppArray elemType size -> 
        showCppType elemType ++ " " ++ name ++ "[" ++ show size ++ "];\n"
      _ -> 
        showCppType varType ++ " " ++ name ++ ";\n"
  CppVariable name varType (Just expr) -> 
    case varType of
      CppArray elemType size -> 
        showCppType elemType ++ " " ++ name ++ "[" ++ show size ++ "] = " ++ showCppExpr expr ++ ";\n"
      _ -> 
        showCppType varType ++ " " ++ name ++ " = " ++ showCppExpr expr ++ ";\n"
  CppCommentDecl comment ->
    "// " ++ comment
  _ -> "// TODO: Render other declaration types\n"

showCppStmt :: CppStmt -> String
showCppStmt = \case
  CppReturn Nothing -> "return;"
  CppReturn (Just expr) -> "return " ++ showCppExpr expr ++ ";"
  CppExprStmt expr -> showCppExpr expr ++ ";"
  CppComment comment -> "// " ++ comment
  _ -> "// TODO: Render other statement types"

showCppExpr :: CppExpr -> String
showCppExpr = \case
  CppVar name -> name
  CppLiteral lit -> showCppLiteral lit
  CppBinary op left right -> 
    showCppExpr left ++ " " ++ op ++ " " ++ showCppExpr right
  CppCall func args ->
    showCppExpr func ++ "(" ++ intercalate ", " (map showCppExpr args) ++ ")"
  _ -> "/* unimplemented expr */"

showCppType :: CppType -> String
showCppType = \case
  CppVoid -> "void"
  CppInt -> "int" 
  CppDouble -> "double"
  CppBool -> "bool"
  CppString -> "std::string"
  CppAuto -> "auto"
  CppVector elemType -> "std::vector<" ++ showCppType elemType ++ ">"
  CppTuple types -> "std::tuple<" ++ intercalate ", " (map showCppType types) ++ ">"
  _ -> "auto"

showCppParam :: CppParam -> String
showCppParam (CppParam name paramType mdefault) = 
  let base = showCppType paramType ++ " " ++ name
  in case mdefault of
       Nothing -> base
       Just defaultValue -> base ++ " = " ++ showCppExpr defaultValue

showCppLiteral :: CppLiteral -> String
showCppLiteral = \case
  CppIntLit i -> show i
  CppFloatLit f -> show f
  CppBoolLit True -> "true"
  CppBoolLit False -> "false" 
  CppStringLit s -> "\"" ++ escapeCppString s ++ "\""
  where
    escapeCppString :: Text -> String
    escapeCppString s = ""