// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// Processing expression: Call

// About to call generatePythonCall

int __debug_generatePythonCall_called = 1;

// Processing expression: Variable

// Processing expression: Literal

// Function call: print with 1 args

int __debug_print = 42;

int __debug_print_args = 1;

// Returned from generatePythonCall

int main() {
    std::cout << "Sum:" << std::endl;
    return 0;
}

