// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <sstream>
#include <tuple>
#include <string>
#include <iostream>

// DEBUG: Processing f-string template: a = {a}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
// DEBUG: Processing f-string template: b = {b}
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parsed into 2 parts
// DEBUG: Generating print with 1 arguments
int main() {
    {
    auto temp_0 = std::make_tuple(1, 2);
    auto a = std::get<0>(temp_0);
    auto b = std::get<1>(temp_0);
}
    std::cout << "a = " << a << std::endl;
    std::cout << "b = " << b << std::endl;
    return 0;
}

