{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}
import Fluxus.CodeGen.CPP
import Fluxus.AST.Common
import Fluxus.AST.Python
import Data.List (intercalate)

-- Create a simple CppCall expression for testing
testExpr :: CppExpr
testExpr = CppCall (CppVar "add") [CppLiteral (CppIntLit 1), CppLiteral (CppIntLit 2)]

main :: IO ()
main = do
  putStrLn "Testing C++ expression rendering..."
  let config = CppGenConfig
        { cgcOptimizationLevel = 2
        , cgcEnableInterop = True
        , cgcTargetCppStd = "c++20"
        , cgcUseSmartPointers = True
        , cgcEnableParallel = True
        , cgcEnableCoroutines = True
        , cgcNamespace = "hyperstatic"
        , cgcHeaderGuard = "HYPERSTATIC_GENERATED"
        }
  let unit = CppUnit ["<iostream>"] [] 
              [ CppFunction "main" CppInt [] 
                  [ CppDecl $ CppVariable "result" CppAuto (Just testExpr)
                  , CppReturn (Just (CppLiteral (CppIntLit 0)))
                  ]
              ]
  putStrLn "Generated C++ code:"
  putStrLn $ showCppUnit unit

showCppUnit :: CppUnit -> String
showCppUnit (CppUnit includes _ decls) = 
  let renderedCode = unlines $
        [ "// Generated by HyperStatic/CXX Compiler - DEBUG VERSION" ] ++
        map (\inc -> "#include " ++ show inc) includes ++
        [ "" ] ++
        map showCppDecl decls
  in renderedCode

showCppDecl :: CppDecl -> String
showCppDecl = \case
  CppFunction name retType params body -> 
    (showCppType retType) ++ " " ++ (show name) ++ "(" ++ 
    (intercalate ", " (map showCppParam params)) ++ ") {\n" ++
    (unlines (map ("    " ++) (map showCppStmt body))) ++
    "}\n"
  CppVariable name varType Nothing -> 
    case varType of
      CppArray elemType size -> 
        (showCppType elemType) ++ " " ++ (show name) ++ "[" ++ (show size) ++ "];\n"
      _ -> 
        (showCppType varType) ++ " " ++ (show name) ++ ";\n"
  CppVariable name varType (Just expr) -> 
    case varType of
      CppArray elemType size -> 
        (showCppType elemType) ++ " " ++ (show name) ++ "[" ++ (show size) ++ "] = " ++ (showCppExpr expr) ++ ";\n"
      _ -> 
        (showCppType varType) ++ " " ++ (show name) ++ " = " ++ (showCppExpr expr) ++ ";\n"
  CppCommentDecl comment ->
    "// " ++ (show comment)
  _ -> "// TODO: Render other declaration types\n"

showCppStmt :: CppStmt -> String
showCppStmt = \case
  CppReturn Nothing -> "return;"
  CppReturn (Just expr) -> "return " ++ (showCppExpr expr) ++ ";"
  CppExprStmt expr -> (showCppExpr expr) ++ ";"
  CppDecl decl -> showCppDecl decl
  CppComment comment -> "// " ++ (show comment)
  _ -> "// TODO: Render other statement types"

showCppExpr :: CppExpr -> String
showCppExpr = \case
  CppVar name -> show name
  CppLiteral lit -> showCppLiteral lit
  CppBinary op left right -> 
    (showCppExpr left) ++ " " ++ (show op) ++ " " ++ (showCppExpr right)
  CppCall func args ->
    (showCppExpr func) ++ "(" ++ (intercalate ", " (map showCppExpr args)) ++ ")"
  _ -> "/* unimplemented expr */"

showCppType :: CppType -> String
showCppType = \case
  CppVoid -> "void"
  CppInt -> "int" 
  CppDouble -> "double"
  CppBool -> "bool"
  CppString -> "std::string"
  CppAuto -> "auto"
  CppVector elemType -> "std::vector<" ++ (showCppType elemType) ++ ">"
  CppTuple types -> "std::tuple<" ++ (intercalate ", " (map showCppType types)) ++ ">"
  _ -> "auto"

showCppParam :: CppParam -> String
showCppParam (CppParam name paramType mdefault) = 
  let base = (showCppType paramType) ++ " " ++ (show name)
  in case mdefault of
       Nothing -> base
       Just defaultValue -> base ++ " = " ++ (showCppExpr defaultValue)

showCppLiteral :: CppLiteral -> String
showCppLiteral = \case
  CppIntLit i -> show i
  CppFloatLit f -> show f
  CppBoolLit True -> "true"
  CppBoolLit False -> "false" 
  CppStringLit s -> "\"" ++ (show s) ++ "\""
  _ -> "/* unimplemented literal */"
