// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto name = "Python";
    std::cout << std::string("Hello ") + std::string(name) << std::endl;
    return 0;
}

