// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 1 arguments
int main() {
    std::cout << "hello" << std::endl;
    return 0;
}

