// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyDict [(Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "key")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 42)})]
// DEBUG: Generating print with 1 arguments
// TODO: Implement Python expression: PySubscript (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "my_dict")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = SliceIndex (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "key")})})
// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
int main() {
    auto my_dict = 0;
    std::cout << "Dict value:" << std::endl;
    std::cout << 0 << std::endl;
    auto a = 42;
    std::cout << "Variable:" << std::endl;
    std::cout << a << std::endl;
    return 0;
}

