// Generated by HyperStatic/CXX Compiler
/* Original Source (./debug_simple.py):
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

def main():
    for i in range(10):
        result = fibonacci(i)
        print("fib(", i, ") = ", result)

main()
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

auto fibonacci(auto n) {
    return 0;
}

auto main_func() {
    return 0;
}

// Expression statement: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyCall (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "main")}) []}

}
using namespace fluxus;

int main() {
    fluxus::main_func();
    return 0;
}

