// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
// DEBUG: Fallback case for function: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "type")}
// DEBUG: Generating print with 1 arguments
int main() {
    auto x = 10;
    auto y = 5;
    auto result = x / y;
    std::cout << "Division result:" << std::endl;
    std::cout << result << std::endl;
    std::cout << "Type of result:" << std::endl;
    std::cout << type(result) << std::endl;
    return 0;
}

