// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// DEBUG: Found 1 module statements
// DEBUG: Generated 1 C++ statements
// DEBUG: Actual statements after filtering: 1
// CppExprStmt (CppBinary "<<" (CppBinary "<<" (CppVar "std::cout") (CppLiteral (CppStringLit "Hello World"))) (CppVar "std::endl"))
// DEBUG: isMainFile = True
// DEBUG: hasMain = False
// DEBUG: Creating main function with statements
int main() {
    std::cout << "Hello World" << std::endl;
    return 0;
}

