// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>
#include "tuple_printer.h"

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

auto add(const std::tuple<int, int>& t) {
    return std::get<0>(t) + std::get<1>(t);
}

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_add = 42;

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_print = 42;

// TODO: Render other declaration types

int main() {
    std::cout << add(std::make_tuple(1, 2)) << std::endl;
    return 0;
}

