// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyComparison [OpLe] [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "n")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 1)}]
auto fact(auto n) {
    if (0) {
    return 1;
}
    return n * fact(n - 1);
}

int main() {
    auto result = fact(4);
    std::cout << result << std::endl;
    return 0;
}

