// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto fibonacci(auto n) {
    if (0) {
    return n;
} else {
    return fibonacci(n - 1) + fibonacci(n - 2);
}
}

int main() {
    return 0;
}

