// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto fib(auto n) {
    if (n <= 1) {
        return n;
    }
    return fib(n - 1) + fib(n - 2);
}

int main() {
    auto result = fib(5);
    std::cout << result << std::endl;
    return 0;
}
