// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto greet(auto name) {
    return "Hello {name}";
}

int main() {
    std::cout << greet("World") << std::endl;
    return 0;
}

