// Generated by HyperStatic/CXX Compiler
#include <cmath>
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

int main() {
    auto x = 10;
    auto y = 20;
    auto sum_result = x + y;
    auto diff = y - x;
    auto product = x * y;
    auto quotient = std::floor(y / x);
    auto remainder = y % x;
    std::cout << "Sum: " + std::to_string(sum_result) << std::endl;
    std::cout << "Difference: " + std::to_string(diff) << std::endl;
    std::cout << "Product: " + std::to_string(product) << std::endl;
    std::cout << "Quotient: " + std::to_string(quotient) << std::endl;
    std::cout << "Remainder: " + std::to_string(remainder) << std::endl;
    return 0;
}