// Generated by HyperStatic/CXX Compiler
#include <chrono>
#include <tuple>
#include <memory>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <vector>
#include <string>
#include <iostream>

int main() {
    fmt.Println("Hello, World!");
    fmt.Printf("2 + 2 = %d\n", 2 + 2);
    return 0;
}

