// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello World" << std::endl;
    auto x = 42;
    std::cout << x << std::endl;
    auto y = 3.14;
    std::cout << y << std::endl;
    auto s = "test";
    std::cout << s << std::endl;
    return 0;
}

