// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto add(auto a, auto b) {
    return a + b;
}

int main() {
    auto x = 42;
    auto y = 3.14;
    auto z = "hello";
    auto result = add(x, 10);
    std::cout << result << std::endl;
    return 0;
}

