// Generated by HyperStatic/CXX Compiler
/* Original Source (minimal_go_demo.go):
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
	fmt.Printf("2 + 2 = %d\n", 2+2)
}
*/

// Generated by HyperStatic/CXX Compiler

// class

