// Generated by HyperStatic/CXX Compiler
/* Original Source (minimal_python.py):
x = 42
y = 3.14
z = "hello"

def add(a, b):
    return a + b

result = add(x, 10)
print(result)
*/

// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>

int add() {
    return 0;
}

int main() {
    int result = 0;
    int i = 0;
    while (i < 1000000) {
    result = result + i % 1000;
    i = i + 1;

}
    std::cout << "14" << std::endl;;
    return 0;
}

