name: fluxus
version: 0.1.0.0
synopsis: High-performance hybrid C++ AOT compiler for Python and Go
description: |
  Fluxus is an experimental hybrid Ahead-of-Time (AOT) compiler 
  that translates high-level languages (initially Python and Go) into 
  highly optimized modern C++ (C++20/23) while maintaining full language 
  compatibility through runtime interoperability.
license: Apache-2.0
license-file: LICENSE
author: Fluxus Team
maintainer: fluxus@example.com
copyright: 2024 Fluxus Team
category: Compiler

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.17 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2

library:
  source-dirs: 
    - src
    - libs/ast/src
    - libs/cli/src
    - libs/codegen/src
    - libs/optimization/src
    - libs/parser/src
    - libs/type-inference/src
  exposed-modules:
    - Fluxus.AST.Common
    - Fluxus.AST.Python
    - Fluxus.AST.Go
    - Fluxus.Parser.Python.Lexer
    - Fluxus.Parser.Python.Parser
    - Fluxus.Parser.Go.Lexer
    - Fluxus.Parser.Go.Parser
    - Fluxus.Analysis.EscapeAnalysis
    - Fluxus.Analysis.OwnershipInference
    - Fluxus.Analysis.ShapeAnalysis
    - Fluxus.Analysis.SmartFallback
    - Fluxus.Analysis.TypeInference
    - Fluxus.Optimization.BasicPasses
    - Fluxus.Optimization.ConstantFolding
    - Fluxus.Optimization.ConstantPropagation
    - Fluxus.Optimization.DeadCodeElimination
    - Fluxus.Optimization.Devirtualization
    - Fluxus.Optimization.Inlining
    - Fluxus.Optimization.Monomorphization
    - Fluxus.Optimization.SizeReduction
    - Fluxus.Optimization.Vectorization
    - Fluxus.CodeGen.CPP
    - Fluxus.CodeGen.Go
    - Fluxus.Runtime.Python
    - Fluxus.Runtime.Go
    - Fluxus.Compiler.Driver
    - Fluxus.Compiler.Config
    - Fluxus.Utils.Pretty
    - Fluxus.Utils.Graph
    - Fluxus.Debug.Logger
    - Fluxus.Debug.CLI
  other-modules:
    - Fluxus.Internal.Types
    - Fluxus.Internal.Monad
    - Fluxus.AST.Go.Common
    - Fluxus.AST.Go.Types
    - Fluxus.AST.Go.Helpers
    - Fluxus.AST.Go.Expressions
  dependencies:
    - containers >= 0.6.7
    - text >= 2.0
    - bytestring >= 0.11
    - mtl >= 2.3
    - transformers >= 0.6
    - parsec >= 3.1.16
    - megaparsec >= 9.5
    - parser-combinators >= 1.3
    - prettyprinter >= 1.7
    - prettyprinter-ansi-terminal >= 1.1
    - hashable >= 1.4
    - unordered-containers >= 0.2.19
    - vector >= 0.13
    - array >= 0.5
    - deepseq >= 1.4
    - filepath >= 1.4
    - directory >= 1.3
    - process >= 1.6
    - temporary >= 1.3
    - optparse-applicative >= 0.17
    - aeson >= 2.1
    - yaml >= 0.11
    - scientific >= 0.3
    - lens >= 5.2
    - fgl >= 5.8
    - monad-logger >= 0.3.40
    - fast-logger >= 3.2
    - ansi-terminal >= 1.1
    - time >= 1.12
    - stm >= 2.5
    - haskeline >= 0.8

executables:
  fluxus:
    main: Main.hs
    source-dirs: app
    dependencies:
      - fluxus
      - optparse-applicative
      - text
      - monad-logger
      - directory
      - filepath
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  fluxus-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - Test.Fluxus.Analysis.EscapeAnalysis
      - Test.Fluxus.Analysis.OwnershipInference
      - Test.Fluxus.Analysis.ShapeAnalysis
      - Test.Fluxus.Analysis.SmartFallback
      - Test.Fluxus.CodeGen.Go
      - Test.Fluxus.EndToEnd
      - Test.Fluxus.Integration
      - Test.Fluxus.Optimization
      - Test.Fluxus.Optimization.ConstantFolding
      - Test.Fluxus.Optimization.DeadCodeElimination
      - Test.Fluxus.Optimization.Inlining
      - Test.Fluxus.Parser.Python
      - Test.Fluxus.Parser.Go
      - Test.Fluxus.Analysis.TypeInference
      - Test.Fluxus.CodeGen.CPP
      - Test.Fluxus.ConvertCommand
      - Test.Fluxus.Runtime.Go
      - Test.Fluxus.Runtime.Python
    dependencies:
      - fluxus
      - hspec >= 2.10
      - hspec-core >= 2.10
      - QuickCheck >= 2.14
      - text
      - containers
      - directory
      - filepath
      - process
      - unix
      - time >= 1.12
      - unordered-containers >= 0.2.19
      - temporary >= 1.3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

benchmarks:
  fluxus-bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - fluxus
      - criterion >= 1.6
      - text
      - deepseq
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

