// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto name = "Bob";
    auto age = 25;
    std::cout << "Hello, {name}! You are {age} years old." << std::endl;
    return 0;
}

