// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto multiply(auto a, auto b, auto c) {
    return a * b * c;
}

int main() {
    auto result = multiply(2, 3, 4);
    std::cout << result << std::endl;
    return 0;
}

