// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto test_func(auto a, auto b) {
    return a + b;
}

int main() {
    std::cout << test_func(1) << std::endl;
    std::cout << test_func(1, 2) << std::endl;
    return 0;
}

