// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello from Python!" << std::endl;
    std::cout << "Basic operations:" << std::endl;
    auto a = 10;
    auto b = 20;
    std::cout << "a =" << " " << a << std::endl;
    std::cout << "b =" << " " << b << std::endl;
    std::cout << "a + b =" << " " << a + b << std::endl;
    std::cout << "a * b =" << " " << a * b << std::endl;
    for (i = 0;; i < 5; ++i) {
    std::cout << "Loop iteration:" << " " << i << std::endl;
}
    std::cout << "Python program completed successfully!" << std::endl;
    return 0;
}

