// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <tuple>
#include <string>
#include <iostream>

// DEBUG: Fallback case for function: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "add")}
int main() {
    auto result = add(std::make_tuple(1, 2));
    return 0;
}

