// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto add(auto a, auto b) {
    return a + b;
}

int main() {
    auto result = add(5, 7);
    std::cout << result << std::endl;
    return 0;
}

