// Generated by HyperStatic/CXX Compiler
#include <chrono>
#include <tuple>
#include <memory>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <vector>
#include <string>
#include <iostream>

int main() {
    /* expr */("Hello");
    /* expr */(" ");
    /* expr */("World!");
    return 0;
}

