// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

auto add(auto a, auto b) {
    return a + b;
}

// DEBUG: Fallback case for function: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "add")}
// DEBUG: Generating print with 1 arguments
int main() {
    auto result = add(5, 3);
    std::cout << result << std::endl;
    return 0;
}

