// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto greet(auto name) {
    return std::string(std::string("Hello, ") + std::string(name)) + std::string("!");
}

auto add(auto a, auto b) {
    return a + b;
}

int main() {
    auto result = greet("World");
    std::cout << result << std::endl;
    std::cout << add(5, 3) << std::endl;
    return 0;
}

