// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_div_explicit.py):
x = 10  # type: int
y = 20  # type: int
z = float(x) / float(y)  # Ensure float division with explicit types to avoid TInt/TFloat unification error
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

}
using namespace fluxus;

int main() {
    auto x = 10;
    auto y = 20;
    auto z = float(x) / float(y);
    return 0;
}

