// Generated by Fluxus C++ Compiler
#include <vector>
#include <sstream>
#include <string>
#include <iostream>

std::vector<long long> numbers = std::vector<long long>{1, 2, 3};

auto evens = 0;

std::string py_bool_to_string(bool value)
{
  if (value)
  {
    return "True";
  }
  else
  {
    return "False";
  }
}

std::string py_float_to_string(double value)
{
  std::ostringstream oss;
  (oss << value);
  std::string result = oss.str();
  if (((result.find(".") == std::string::npos) && ((result.find("e") == std::string::npos) && (result.find("E") == std::string::npos))))
  {
    result.append(".0");
  }
  return result;
}

int main()
{
  return 0;
}