// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    std::cout << "Simple test" << std::endl;
    std::cout << 1 + 1 << std::endl;
    std::cout << 2 * 3 << std::endl;
    return 0;
}

