// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// Processing expression: Call

// About to call generatePythonCall

int __debug_generatePythonCall_called = 1;

// Processing expression: Variable

// Processing expression: Literal

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "hello")})}

int __debug_print = 42;

int __debug_print_args = 1;

// print function called with 1 arguments

// print argument 0: CppLiteral (CppStringLit "hello")

// print printable argument 0: CppLiteral (CppStringLit "hello")

// Final printable arg type: CppLiteral (CppStringLit "hello")

// Returned from generatePythonCall

int main() {
    std::cout << "hello" << std::endl;
    return 0;
}

