// Generated by Fluxus C++ Compiler
#include <vector>
#include <sstream>
#include <string>
#include <iostream>

auto repeated;

std::string py_bool_to_string(bool value)
{
  if (value)
  {
    return "True";
  }
  else
  {
    return "False";
  }
}

std::string py_float_to_string(double value)
{
  std::ostringstream oss;
  (oss << value);
  std::string result = oss.str();
  if (((result.find(".") == std::string::npos) && ((result.find("e") == std::string::npos) && (result.find("E") == std::string::npos))))
  {
    result.append(".0");
  }
  return result;
}

std::vector<long long> range(long long n)
{
  std::vector<long long> result;
  result.reserve(n);
  for (long long i = 0; (i < n); ++i)
  {
    result.push_back(i);
  }
  return result;
}

std::string fluxus_repeat_string(const std::string& value, long long count)
{
  if ((count <= 0))
  {
    return "";
  }
  std::string result = "";
  for (long long i = 0; (i < count); ++i)
  {
    (result += value);
  }
  return result;
}

int main()
{
  const std::string __name__ = "__main__";
  (repeated = fluxus_repeat_string("ha", (long long)3));
  ((std::cout << repeated) << std::endl);
  return 0;
}