// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: generateCppFromPython called
// DEBUG: This should appear in the output
// DEBUG: Found 0 function definitions
// DEBUG: Found 1 module statements
// DEBUG: Inside print function handler
int main() {
    std::cout << 1 << " " << 2 << " " << 3 << std::endl;
    return 0;
}

