// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: testIfElse
void testIfElse() {
    std::cout << "=== Testing If-Else ===" << std::endl;
    double x = 10.0;
    double y = 20.0;
    if (x > y) {
    {
    std::cout << "x is greater than y" << std::endl;
}
} else {
    if (x < y) {
    {
    std::cout << "x is less than y" << std::endl;
}
} else {
    {
    std::cout << "x is equal to y" << std::endl;
}
}
}
    if (result > 25.0) {
    {
    std::cout << "Sum (" << result << ") is greater than 25" << std::endl;
}
}
    if (x > 5.0) {
    {
    if (y > 15.0) {
    {
    std::cout << "Both x > 5 and y > 15" << std::endl;
}
}
}
}
}

// Generating function: testForLoops
void testForLoops() {
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

