// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 0 declarations
// No declarations found in Go file - parser may need to be fixed
// Generating main function
int main() {
    // Struct definition
    struct Person {
        std::string Name;
        int Age;
        
        // Method with value receiver
        std::string Greet() {
            return "Hello, my name is " + Name + " and I'm " + std::to_string(Age) + " years old.";
        }
        
        // Method with pointer receiver (simulated with reference)
        void HaveBirthday() {
            Age++;
        }
    };
    
    // Another struct
    struct Animal {
        std::string Name;
        std::string Species;
        
        // Animal implements Greeter
        std::string Greet() {
            return "Hi, I'm " + Name + " the " + Species + ".";
        }
    };
    
    // Create struct instances
    Person person = {"Alice", 25};
    Animal animal = {"Rex", "dog"};
    
    // Use methods
    std::cout << "Before birthday: " << person.Greet() << std::endl;
    person.HaveBirthday();
    std::cout << "After birthday: " << person.Greet() << std::endl;
    
    // Use interface (simulated with function calls)
    std::cout << person.Greet() << std::endl;
    std::cout << animal.Greet() << std::endl;
    
    // Test multiple assignment
    int a = 10, b = 20;
    std::cout << "a = " << a << ", b = " << b << std::endl;
    
    // Test struct field access
    std::cout << "Person details: Name=" << person.Name << ", Age=" << person.Age << std::endl;
    
    return 0;
}

