// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
// TODO: Render other declaration types

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
int main() {
    double a = 5.0;
    double b = 3.0;
    std::cout << a + b << std::endl;
    return 0;
}

