// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto x = 10;
    auto y = 20;
    std::cout << x == y << std::endl;
    std::cout << x != y << std::endl;
    std::cout << x < y << std::endl;
    std::cout << x > y << std::endl;
    return 0;
}

