// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
// TODO: Render other declaration types

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
int main() {
    double x = 10.0;
    double y = 20.0;
    auto z = x + y;
    std::cout << z << std::endl;
    return 0;
}

