// Generated by HyperStatic/CXX Compiler
#include <chrono>
#include <tuple>
#include <memory>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <vector>
#include <string>
#include <iostream>

int add(int a, int b) {
    return a + b;
}

int main() {
    auto result = add(5, 3);
    std::cout << "5 + 3 = " << result << std::endl;
    return 0;
}

