// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_just_x.py):
x
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

// Expression statement: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "x")}

}
using namespace fluxus;

int main() {
    x;
    return 0;
}

