// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

void test() {
    auto i = 5;
    auto result = 8;
    std::cout << "fib({i}) = {result}" << std::endl;
}

int main() {
    return 0;
}

