// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
// TODO: Implement Go expression: GoAddress (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "x")})
// TODO: Implement Go expression: GoDeref (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "p")})
int main() {
    double x = 42.0;
    auto p = 0;
    0 = 21.0;
    std::cout << "x = " << x << std::endl;
    return 0;
}

