// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 3 declarations
// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: multiply
int multiply(int a, int b) {
    return a * b;
}

// Generating function: testIfElse
int testIfElse(int x) {
    if (x > 10.0) {
    {
    return "greater than 10";
}
} else {
    if (x < 5.0) {
    {
    return "less than 5";
}
} else {
    {
    return "between 5 and 10";
}
}
}
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

