// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto greet(auto name) {
    return std::string("Hello, ") + std::string(name);
}

auto power(auto base, auto exponent) {
    return base + exponent;
}

auto factorial(auto n) {
    if (n <= 1) {
    return 1;
}
    return n * factorial(n - 1);
}

int main() {
    std::cout << greet("World") << std::endl;
    std::cout << power(3, 2) << std::endl;
    std::cout << power(3, 3) << std::endl;
    std::cout << factorial(5) << std::endl;
    return 0;
}

