// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_div_literals.py):
z = float(10) / float(20)  # Ensure float division with explicit types
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

}
using namespace fluxus;

int main() {
    auto z = float(10) / float(20);
    return 0;
}

