// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

int main() {
    auto x = 10;
    auto y = 10;
    auto z = y / x;
    return 0;
}

