// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

int main() {
    std::cout << std::make_tuple("Hello", 42) << std::endl;
    return 0;
}

