// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: testBasicTypes
void testBasicTypes() {
    std::cout << "=== Test 1: Basic Types ===" << std::endl;
    auto intVar = 42.0;
    auto floatVar = 3.14;
    auto stringVar = "Hello";
    auto boolVar = true;
    std::cout << "int: " << intVar << std::endl;
    std::cout << "float: " << floatVar << std::endl;
    std::cout << "string: %s" << std::endl;
    std::cout << "bool: %t" << std::endl;
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

