// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 1 arguments
int main() {
    auto s1 = "Hello";
    auto s2 = "World";
    auto result = std::string(s1) + std::string(" ") + s2;
    std::cout << result << std::endl;
    return 0;
}

