// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_div_same.py):
x = 10
y = 10
z = float(x) / float(y)  # Ensure float division with explicit types
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

}
using namespace fluxus;

int main() {
    auto x = 10;
    auto y = 10;
    auto z = float(x) / float(y);
    return 0;
}

