// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <array>
#include <tuple>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

void print_vector_int(std::vector<int>& vec) {
    std::cout << "[";
    bool first = true;
    size_t i = 0;
    for (; i < vec.size(); ++i) {
    if (!first) {
    std::cout << ", ";
}
    std::cout << vec[i];
    first = false;
}
    std::cout << "]";
}

void print_array_int(std::initializer_list<int>& arr) {
    std::cout << "[";
    bool first = true;
    auto it = arr.begin();
    while (it != arr.end()) {
    if (!first) {
    std::cout << ", ";
}
    std::cout << *it;
    first = false;
    ++it;
}
    std::cout << "]";
}

std::ostream& operator<<(std::ostream& os, std::vector<int>& vec) {
    os << "[";
    bool first = true;
    for (auto it = vec.begin(); it != vec.end(); ++it) {
    if (!first) {
    os << ", ";
}
    os << *it;
    first = false;
}
    os << "]";
    return os;
}

std::ostream& operator<<(std::ostream& os, std::initializer_list<int>& lst) {
    os << "[";
    bool first = true;
    for (auto it = lst.begin(); it != lst.end(); ++it) {
    if (!first) {
    os << ", ";
}
    os << *it;
    first = false;
}
    os << "]";
    return os;
}

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 5 declarations
// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: swap
std::tuple<std::string, std::string> swap(std::string a, std::string b) {
    return std::make_tuple(b, a);
}

// Generating function: max
int max(int a, int b) {
    if (a > b) {
    return a;
} else {
    return b;
}
}

// Generating function: fibonacci
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLe (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "n")})}
int fibonacci(int n) {
    if (n <= 1) {
    return n;
}
    int a = 0;
    int b = 1;
    for (int i = 2; i <= n; ++i) {
    auto temp_0 = b;
    auto temp_1 = a + b;
    a = temp_0;
    b = temp_1;
}
    return b;
}

// Generating function: processArray
void processArray() {
    auto arr = {1, 2, 3};
    auto slice = std::vector<int>{4, 5, 6};
    std::cout << "Array:" << " " << arr << std::endl;
    std::cout << "Slice:" << " " << slice << std::endl;
}

// No main function found in declarations - this might be expected for some files
