// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
int main() {
    std::cout << "Hello, world!\n" << std::endl;
    std::cout << "The answer is %d\n" << 42.0 << std::endl;
    std::cout << "Pi is approximately %.2f\n" << 3.14159 << std::endl;
    std::cout << "Name: %s, Age: %d\n" << "Alice" << 25.0 << std::endl;
    std::cout << "Multiple values: %d + %d = %d\n" << 5.0 << 3.0 << 8.0 << std::endl;
    std::cout << "Column1\tColumn2\tColumn3\n" << std::endl;
    std::cout << "Quote test: \"Hello\"\n" << std::endl;
    std::cout << "Backslash test: \\n\n" << std::endl;
    return 0;
}

