// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyBoolOp OpAnd [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)})
int main() {
    auto x = 42;
    auto y = 3.14;
    auto s = "Hello";
    auto b = true;
    auto n = nullptr;
    std::cout << x << std::endl;
    std::cout << y << std::endl;
    std::cout << s << std::endl;
    std::cout << b << std::endl;
    std::cout << n << std::endl;
    std::cout << 5 + 3 << std::endl;
    std::cout << 5 - 3 << std::endl;
    std::cout << 5 * 3 << std::endl;
    std::cout << 5 / 3 << std::endl;
    std::cout << 5 == 5 << std::endl;
    std::cout << 5 > 3 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    if (x > 0) {
    std::cout << "x is positive" << std::endl;
} else {
    std::cout << "x is not positive" << std::endl;
}
    auto i = 0;
    for (int j = 0; j < 3; ++j) {
    std::cout << j << std::endl;
}
    return 0;
}

