// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// Processing expression: Call

// About to call generatePythonCall

int __debug_generatePythonCall_called = 1;

// Processing expression: Variable

// Processing expression: Literal

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "Hello, World!")})}

int __debug_print = 42;

int __debug_print_args = 1;

// print function called with 1 arguments

// print argument 0: CppLiteral (CppStringLit "Hello, World!")

// Returned from generatePythonCall

// Processing expression: Literal

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Processing expression: FString

// Processing expression: Variable

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyFString [FStringExpr {fstrExpr = Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "x")}, fstrConversion = Nothing, fstrFormatSpec = Nothing}]})}

// print function called with 1 arguments

// print argument 0: CppVar "x"

// Returned from generatePythonCall

int main() {
    std::cout << "Hello, World!" << std::endl;
    auto x = 42;
    std::cout << x << std::endl;
    return 0;
}

