// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 3 declarations
// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: multiply
int multiply(int a, int b) {
    return a * b;
}

// Generating function: testIfElse
std::string testIfElse(int x) {
    if (x > 10) {
        return "greater than 10";
    } else if (x < 5) {
        return "less than 5";
    } else {
        return "between 5 and 10";
    }
}

// Test for loops
int testForLoop() {
    int sum = 0;
    for (int i = 1; i <= 10; i++) {
        sum += i;
    }
    return sum;
}

// Test while-like loops
int testWhileLoop() {
    int sum = 0;
    int i = 1;
    while (i <= 10) {
        sum += i;
        i++;
    }
    return sum;
}

// Test infinite loops with break
int testInfiniteLoop() {
    int sum = 0;
    int i = 1;
    while (true) {
        if (i > 10) {
            break;
        }
        sum += i;
        i++;
    }
    return sum;
}

// Test switch statements
std::string testSwitch(std::string day) {
    if (day == "Monday") {
        return "Work day";
    } else if (day == "Tuesday") {
        return "Work day";
    } else if (day == "Wednesday") {
        return "Work day";
    } else if (day == "Thursday") {
        return "Work day";
    } else if (day == "Friday") {
        return "Work day";
    } else if (day == "Saturday") {
        return "Weekend";
    } else if (day == "Sunday") {
        return "Weekend";
    } else {
        return "Invalid day";
    }
}

// Generating main function
int main() {
    // Test functions
    std::cout << "Testing functions:" << std::endl;
    std::cout << "add(5, 3) = " << add(5, 3) << std::endl;
    std::cout << "multiply(4, 7) = " << multiply(4, 7) << std::endl;
    
    // Test control flow
    std::cout << "\nTesting control flow:" << std::endl;
    std::cout << "testIfElse(15) = " << testIfElse(15) << std::endl;
    std::cout << "testIfElse(3) = " << testIfElse(3) << std::endl;
    std::cout << "testIfElse(7) = " << testIfElse(7) << std::endl;
    
    // Test loops
    std::cout << "\nTesting loops:" << std::endl;
    std::cout << "testForLoop() = " << testForLoop() << std::endl;
    std::cout << "testWhileLoop() = " << testWhileLoop() << std::endl;
    std::cout << "testInfiniteLoop() = " << testInfiniteLoop() << std::endl;
    
    // Test switch
    std::cout << "\nTesting switch:" << std::endl;
    std::cout << "testSwitch(\"Monday\") = " << testSwitch("Monday") << std::endl;
    std::cout << "testSwitch(\"Saturday\") = " << testSwitch("Saturday") << std::endl;
    std::cout << "testSwitch(\"Invalid\") = " << testSwitch("Invalid") << std::endl;
    
    return 0;
}

// Test for loops
int testForLoop() {
    int sum = 0;
    for (int i = 1; i <= 10; i++) {
        sum += i;
    }
    return sum;
}

// Test while-like loops
int testWhileLoop() {
    int sum = 0;
    int i = 1;
    while (i <= 10) {
        sum += i;
        i++;
    }
    return sum;
}

// Test infinite loops with break
int testInfiniteLoop() {
    int sum = 0;
    int i = 1;
    while (true) {
        if (i > 10) {
            break;
        }
        sum += i;
        i++;
    }
    return sum;
}

// Test switch statements
std::string testSwitch(std::string day) {
    if (day == "Monday") {
        return "Work day";
    } else if (day == "Tuesday") {
        return "Work day";
    } else if (day == "Wednesday") {
        return "Work day";
    } else if (day == "Thursday") {
        return "Work day";
    } else if (day == "Friday") {
        return "Work day";
    } else if (day == "Saturday") {
        return "Weekend";
    } else if (day == "Sunday") {
        return "Weekend";
    } else {
        return "Invalid day";
    }
}

