// Generated by Fluxus C++ Compiler
#include <any>
#include <vector>
#include <sstream>
#include <string>
#include <iostream>

std::string py_bool_to_string(bool value)
{
  if (value)
  {
    return "True";
  }
  else
  {
    return "False";
  }
}

std::string py_float_to_string(double value)
{
  std::ostringstream oss;
  (oss << value);
  std::string result = oss.str();
  if (((result.find(".") == std::string::npos) && ((result.find("e") == std::string::npos) && (result.find("E") == std::string::npos))))
  {
    result.append(".0");
  }
  return result;
}

std::vector<long long> range(long long n)
{
  std::vector<long long> result;
  result.reserve(n);
  for (long long i = 0; (i < n); ++i)
  {
    result.push_back(i);
  }
  return result;
}

std::any pair_sum(auto a, auto b)
{
  std::vector<std::any> values = std::vector<std::any>{a, b, (a + b)};
  return values[2];
}

int main()
{
  const std::string __name__ = "__main__";
  ((std::cout << pair_sum(3, 4)) << std::endl);
  return 0;
}