// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>
#include "tuple_printer.h"

int main() {
    std::cout << std::make_tuple("Testing division: 10 / 5 =", 10.0 / 5.0) << std::endl;
    return 0;
}

