// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyBoolOp OpAnd [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// TODO: Implement Python expression: PyBoolOp OpOr [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)})
int main() {
    std::cout << "Testing basic Python..." << std::endl;
    auto x = 42;
    auto y = 3.14;
    auto s = "hello";
    auto b = true;
    std::cout << x << std::endl;
    std::cout << y << std::endl;
    std::cout << s << std::endl;
    std::cout << b << std::endl;
    std::cout << 5 + 3 << std::endl;
    std::cout << 5 - 3 << std::endl;
    std::cout << 5 * 3 << std::endl;
    std::cout << 5 / 3 << std::endl;
    std::cout << std::string(std::string("hello") + std::string(" ")) + std::string("world") << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    auto age = 25;
    if (age >= 18) {
    std::cout << "adult" << std::endl;
} else {
    std::cout << "minor" << std::endl;
}
    auto i = 0;
    for (int j = 0; j < 3; ++j) {
    std::cout << "for:" << " " << j << std::endl;
}
    std::cout << "Basic test complete!" << std::endl;
    return 0;
}

