// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_add_vars.py):
x = 10
y = 20
z = x + y
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

}
using namespace fluxus;

int main() {
    auto x = 10;
    auto y = 20;
    auto z = x + y;
    return 0;
}

