// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 3 declarations
// Generating variable declaration(s)
int globalInt = 42;

// Generating variable declaration(s)
std::string globalString = "Hello, World!";

// Generating variable declaration(s)
bool globalBool = true;

// Generating main function
int main() {
    // Local variable declarations
    int localInt = 10;
    std::string localString = "Local variable";
    bool localBool = false;
    
    // Short variable declarations
    int shortInt = 20;
    std::string shortString = "Short declaration";
    bool shortBool = true;
    
    // Multiple variable declarations
    int a = 1, b = 2, c = 3;
    std::string x = "hello", y = "world";
    
    // Type inference
    int inferredInt = 100;
    std::string inferredString = "inferred";
    double inferredFloat = 3.14;
    
    // Print basic variables
    std::cout << "=== Basic Variables Test ===" << std::endl;
    std::cout << "Global variables:" << std::endl;
    std::cout << "  globalInt: " << globalInt << std::endl;
    std::cout << "  globalString: " << globalString << std::endl;
    std::cout << "  globalBool: " << (globalBool ? "true" : "false") << std::endl;
    
    std::cout << "Local variables:" << std::endl;
    std::cout << "  localInt: " << localInt << std::endl;
    std::cout << "  localString: " << localString << std::endl;
    std::cout << "  localBool: " << (localBool ? "true" : "false") << std::endl;
    
    std::cout << "Short declarations:" << std::endl;
    std::cout << "  shortInt: " << shortInt << std::endl;
    std::cout << "  shortString: " << shortString << std::endl;
    std::cout << "  shortBool: " << (shortBool ? "true" : "false") << std::endl;
    
    std::cout << "Multiple declarations:" << std::endl;
    std::cout << "  a, b, c: " << a << " " << b << " " << c << std::endl;
    std::cout << "  x, y: " << x << " " << y << std::endl;
    
    std::cout << "Type inference:" << std::endl;
    std::cout << "  inferredInt: " << inferredInt << std::endl;
    std::cout << "  inferredString: " << inferredString << std::endl;
    std::cout << "  inferredFloat: " << inferredFloat << std::endl;
    
    // Constants
    const double Pi = 3.14159;
    const int MaxInt = 2147483647; // Simplified for example
    
    std::cout << "Constants:" << std::endl;
    std::cout << "  Pi: " << Pi << std::endl;
    std::cout << "  MaxInt: " << MaxInt << std::endl;
    
    // Basic arithmetic operations
    int sum = a + b + c;
    int product = a * b * c;
    int difference = a - b;
    int quotient = a / b;
    int remainder = a % b;
    
    std::cout << "Arithmetic operations:" << std::endl;
    std::cout << "  Sum: " << sum << std::endl;
    std::cout << "  Product: " << product << std::endl;
    std::cout << "  Difference: " << difference << std::endl;
    std::cout << "  Quotient: " << quotient << std::endl;
    std::cout << "  Remainder: " << remainder << std::endl;
    
    // Basic functions test
    int result = add(5, 3);
    std::cout << "Function call add(5, 3): " << result << std::endl;
    
    int result2 = multiply(4, 7);
    std::cout << "Function call multiply(4, 7): " << result2 << std::endl;
    
    // Basic control flow
    if (result > 10) {
        std::cout << "Result is greater than 10" << std::endl;
    } else {
        std::cout << "Result is less than or equal to 10" << std::endl;
    }
    
    // For loop
    std::cout << "For loop test:" << std::endl;
    for (int i = 0; i < 5; i++) {
        std::cout << "  i = " << i << std::endl;
    }
    
    // While-like loop
    std::cout << "While-like loop test:" << std::endl;
    int j = 0;
    while (j < 3) {
        std::cout << "  j = " << j << std::endl;
        j++;
    }
    
    // Infinite loop with break
    std::cout << "Infinite loop with break test:" << std::endl;
    int k = 0;
    while (true) {
        if (k >= 2) {
            break;
        }
        std::cout << "  k = " << k << std::endl;
        k++;
    }
    
    std::cout << "Basic test completed successfully!" << std::endl;
    
    return 0;
}

// Function implementations
int add(int a, int b) {
    return a + b;
}

int multiply(int a, int b) {
    return a * b;
}

