// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: add
int add(int a, int b) {
    return a + b;
}

// Generating function: main
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLt (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoInt 3)})}
int main() {
    int x = 10;
    auto y = 20;
    int z = 30;
    auto sum = x + y + z;
    std::cout << "x:" << " " << x << std::endl;
    std::cout << "y:" << " " << y << std::endl;
    std::cout << "z:" << " " << z << std::endl;
    std::cout << "sum:" << " " << sum << std::endl;
    if (sum > 50) {
    {
    std::cout << "Sum is greater than 50" << std::endl;
}
}
    for (int i = 0; i < 3; ++i) {
    std::cout << "Loop iteration:" << " " << i << std::endl;
}
    auto result = add(x, y);
    std::cout << "add(x, y):" << " " << result << std::endl;
    return 0;
}

