// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto name = "Fluxus";
    auto version = "1.0";
    auto full_name = name + " " + version;
    std::cout << full_name << std::endl;
    std::cout << "Upper: {name.upper()}" << std::endl;
    std::cout << "Lower: {name.lower()}" << std::endl;
    std::cout << "Length: {len(name)}" << std::endl;
    std::cout << "Welcome to {name} v{version}" << std::endl;
    return 0;
}

