// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: testVariables
// Complex variable declaration not fully implemented
// Multiple variable definition not fully implemented
void testVariables() {
    std::cout << "=== Testing Variables and Types ===" << std::endl;
    int x = 42.0;
    double y = 3.14;
    std::string z = "Hello";
    bool b = true;
    std::cout << "int: %d, float64: %f, string: %s, bool: %t\n" << x << y << z << b << std::endl;
    double a = 100.0;
    std::string c = "World";
    double d = 2.718;
    std::cout << "inferred int: %d, string: %s, float64: %f\n" << a << c << d << std::endl;
    // Complex variable declaration
    // Multiple variable definition
    std::cout << "multiple: %d, %d, %d, %d\n" << i << j << k << l << std::endl;
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

