// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyUnaryOp OpNegate (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 17)})
// TODO: Implement Python expression: PyUnaryOp OpNegate (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyFloat 2.5)})
int main() {
    auto x = 42;
    auto y = 0;
    auto z = 0;
    auto a = 3.14;
    auto b = 0;
    auto c = 0.0;
    auto s1 = "Hello";
    auto s2 = "Python";
    auto t = true;
    auto f = false;
    auto n = nullptr;
    std::cout << x << std::endl;
    std::cout << y << std::endl;
    std::cout << z << std::endl;
    std::cout << a << std::endl;
    std::cout << b << std::endl;
    std::cout << c << std::endl;
    std::cout << s1 << std::endl;
    std::cout << s2 << std::endl;
    std::cout << t << std::endl;
    std::cout << f << std::endl;
    std::cout << n << std::endl;
    return 0;
}

