// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: generateCppFromPython called
// DEBUG: This should appear in the output
// DEBUG: Found 0 function definitions
// DEBUG: Found 17 module statements
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// TODO: Implement Python expression: PyBoolOp OpAnd [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// DEBUG: Inside print function handler
// TODO: Implement Python expression: PyBoolOp OpOr [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// DEBUG: Inside print function handler
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)})
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
int main() {
    std::cout << "=== Testing Division ===" << std::endl;
    auto result1 = 10 / 2;
    std::cout << "10 / 2 = " << " " << result1 << std::endl;
    auto result2 = 10 / 3;
    std::cout << "10 / 3 = " << " " << result2 << std::endl;
    auto result3 = 15 / 4;
    std::cout << "15 / 4 = " << " " << result3 << std::endl;
    std::cout << "" << std::endl;
    std::cout << "=== Testing Booleans ===" << std::endl;
    auto flag = true;
    std::cout << "True = " << " " << flag << std::endl;
    std::cout << "False = " << " " << false << std::endl;
    std::cout << "True and False = " << " " << 0 << std::endl;
    std::cout << "True or False = " << " " << 0 << std::endl;
    std::cout << "not True = " << " " << 0 << std::endl;
    std::cout << "" << std::endl;
    std::cout << "=== Test Complete ===" << std::endl;
    return 0;
}

