// Generated by HyperStatic/CXX Compiler
/* Original Source (./test_assignment_partial.py):
x = 0
*/

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cmath>
#include <sstream>
namespace fluxus {

}
using namespace fluxus;

int main() {
    auto x = 0;
    return 0;
}

