// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

auto power(auto base, auto exponent) {
    return base + exponent;
}

int main() {
    std::cout << power(5) << std::endl;
    std::cout << power(5, 3) << std::endl;
    return 0;
}

