// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// DEBUG: Starting function generation for: simple_func

// DEBUG: Function has 1 body statements

// Processing expression: Literal

// DEBUG: Generated 1 C++ statements

auto simple_func() {
    return 42;
}

// DEBUG: Starting function generation for: main

// DEBUG: Function has 2 body statements

// Processing expression: Call

// About to call generatePythonCall

int __debug_generatePythonCall_called = 1;

// Processing expression: Variable

// Function call: simple_func with 0 args

int __debug_simple_func = 42;

int __debug_simple_func_args = 0;

// Regular function call: simple_func

int __debug_simple_func_result = 1;

// Returned from generatePythonCall

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Processing expression: Variable

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "result")})}

int __debug_print = 42;

int __debug_print_args = 1;

// print function called with 1 arguments

// print argument 0: CppVar "result"

// Returned from generatePythonCall

// DEBUG: Generated 2 C++ statements

int main() {
    auto result = simple_func();
    std::cout << result << std::endl;
    return 0;
}

// Processing expression: Comparison

// Processing expression: Variable

// Processing expression: Literal

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Function call: main with 0 args

int __debug_main = 42;

int __debug_main_args = 0;

// Regular function call: main

int __debug_main_result = 1;

// Returned from generatePythonCall

