// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

int main() {
    std::cout << 10.0 / 5.0 << std::endl;
    return 0;
}

