// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyBoolOp OpAnd [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// TODO: Implement Python expression: PyBoolOp OpOr [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool False)}]
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyBool True)})
int main() {
    auto x = 42;
    auto y = 3.14;
    auto s = "Hello";
    auto b = true;
    std::cout << x << std::endl;
    std::cout << y << std::endl;
    std::cout << s << std::endl;
    std::cout << b << std::endl;
    std::cout << 5 + 3 << std::endl;
    std::cout << 5 - 3 << std::endl;
    std::cout << 5 * 3 << std::endl;
    std::cout << 5 / 3 << std::endl;
    auto s1 = "Hello";
    auto s2 = "World";
    std::cout << std::string(s1) + std::string(" ") + s2 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    auto age = 25;
    if (age >= 18) {
    std::cout << "Adult" << std::endl;
} else {
    std::cout << "Minor" << std::endl;
}
    auto count = 0;
    for (int i = 0; i < 3; ++i) {
    std::cout << "For loop:" << " " << i << std::endl;
}
    return 0;
}

