// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <tuple>
#include <string>
#include <iostream>

auto calculate() {
    auto x = 2 + 3 * 4;
    auto y = 10 - 5;
    auto z = x * y;
    return z;
}

// DEBUG: Generating print with 1 arguments
int main() {
    auto result = calculate();
    std::cout << std::make_tuple("Result:", result) << std::endl;
    return 0;
}

// DEBUG: PyComparison ops=[OpEq] exprs=[Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "__name__")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "__main__")}]
// DEBUG: Single comparison OpEq -> ==
// IF condition: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyComparison [OpEq] [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "__name__")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyString "__main__")}]}
