// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyUnaryOp OpNegate (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 17)})
// TODO: Implement Python expression: PyUnaryOp OpNegate (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyFloat 2.5)})
int main() {
    std::cout << "=== Testing Variables and Data Types ===" << std::endl;
    auto x = 42;
    auto y = 0;
    auto z = 0;
    std::cout << "Integers: {x}, {y}, {z}" << std::endl;
    auto a = 3.14159;
    auto b = 0;
    auto c = 0.0;
    std::cout << "Floats: {a}, {b}, {c}" << std::endl;
    auto s1 = "Hello, World!";
    auto s2 = "Python";
    auto s3 = "Multi-line
string";
    std::cout << "Strings: {s1}, {s2}, {s3}" << std::endl;
    auto t = true;
    auto f = false;
    std::cout << "Booleans: {t}, {f}" << std::endl;
    auto n = nullptr;
    std::cout << "None: {n}" << std::endl;
    std::cout << "Type of x: {type(x)}" << std::endl;
    std::cout << "Type of a: {type(a)}" << std::endl;
    std::cout << "Type of s1: {type(s1)}" << std::endl;
    std::cout << "Type of t: {type(t)}" << std::endl;
    std::cout << "Type of n: {type(n)}" << std::endl;
    std::cout << "=== Variables and Data Types Test Complete ===
" << std::endl;
    return 0;
}

