// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << "Hello World" << std::endl;
    std::cout << 42 << std::endl;
    auto x = 100;
    std::cout << x << std::endl;
    return 0;
}

