// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 2 arguments
int main() {
    std::cout << "x =" << " " << 10 << std::endl;
    return 0;
}

