// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 1 arguments
// DEBUG: Generating print with 1 arguments
int main() {
    std::cout << "Hello Python" << std::endl;
    std::cout << 42 << std::endl;
    return 0;
}

