// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    std::cout << "=== Testing Operators ===" << std::endl;
    std::cout << "Arithmetic Operators:" << std::endl;
    auto a = 10;
    auto b = 3;
    std::cout << "Addition: {a} + {b} = {a + b}" << std::endl;
    std::cout << "Subtraction: {a} - {b} = {a - b}" << std::endl;
    std::cout << "Multiplication: {a} * {b} = {a * b}" << std::endl;
    std::cout << "Division: {a} / {b} = {a / b}" << std::endl;
    std::cout << "Floor division: {a} // {b} = {a // b}" << std::endl;
    std::cout << "Modulus: {a} % {b} = {a % b}" << std::endl;
    std::cout << "Exponentiation: {a} ** {b} = {a ** b}" << std::endl;
    std::cout << "
Comparison Operators:" << std::endl;
    auto x = 5;
    auto y = 10;
    std::cout << "Equal: {x} == {y} = {x == y}" << std::endl;
    std::cout << "Not equal: {x} != {y} = {x != y}" << std::endl;
    std::cout << "Greater than: {x} > {y} = {x > y}" << std::endl;
    std::cout << "Less than: {x} < {y} = {x < y}" << std::endl;
    std::cout << "Greater than or equal: {x} >= {y} = {x >= y}" << std::endl;
    std::cout << "Less than or equal: {x} <= {y} = {x <= y}" << std::endl;
    std::cout << "
Logical Operators:" << std::endl;
    auto p = true;
    auto q = false;
    std::cout << "AND: {p} and {q} = {p and q}" << std::endl;
    std::cout << "OR: {p} or {q} = {p or q}" << std::endl;
    std::cout << "NOT: not {p} = {not p}" << std::endl;
    std::cout << "NOT: not {q} = {not q}" << std::endl;
    std::cout << "=== Operators Test Complete ===
" << std::endl;
    return 0;
}

