// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: add
auto add(auto a) {
    return a + b;
}

// Generating function: main
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLt (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 3.0)})}
// TODO: Implement Go expression: GoCompositeLit (Just (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoSliceType (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoTypeParam (Identifier "int") Nothing})})) [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 1.0)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 2.0)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 3.0)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 4.0)},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoLiteral (GoFloat 5.0)}]
// TODO: Implement Go builtin: GoLen
// TODO: Implement Go builtin: GoMin
// TODO: Implement Go builtin: GoMax
int main() {
    double x = 10.0;
    double y = 20.0;
    auto result = add(x, y);
    std::cout << "add(%d, %d) = %d
";
    for (double i = 0.0; i < 3.0; ++i) {
    std::cout << "Loop iteration: " << i << std::endl;
}
    auto numbers = 0;
    std::cout << "Numbers: %v" << std::endl;
    std::cout << "Length: " << 0 << std::endl;
    std::cout << "min(10, 5) = " << 0 << std::endl;
    std::cout << "max(10, 5) = " << 0 << std::endl;
    return 0;
}

