// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto x = 10;
    if (x > 5) {
    std::cout << "big" << std::endl;
} else {
    std::cout << "small" << std::endl;
}
    return 0;
}

