// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

int main() {
    auto a = 42;
    std::cout << a << std::endl;
    auto pi = 3.14159;
    std::cout << pi << std::endl;
    auto flag = true;
    std::cout << flag << std::endl;
    auto name = "Python";
    std::cout << name << std::endl;
    return 0;
}

