// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
struct Channel {
    std::queue<T> data_queue;
    std::mutex mutex;
    std::condition_variable cv;
    Channel() {
        // Initialize empty channel
    }
    void send(T value) {
        std::lock_guard<std::mutex> lock = std::lock_guard(this->mutex);
        this->data_queue.push(value);
        this->cv.notify_one();
    }
    T receive() {
        std::unique_lock<std::mutex> lock = std::unique_lock(this->mutex);
        this->cv.wait(lock);
        T result = this->data_queue.front();
        this->data_queue.pop();
        return result;
    }
};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
int main() {
    std::string name = "测试";
    int age = 25;
    double score = 95.5;
    bool passed = true;
    std::cout << "学生 " << name << " 年龄 " << age << " 岁，得分 " << std::fixed << std::setprecision(1) << score << " 分，通过: " << std::boolalpha << passed << std::endl;
    double pi = 3.14159;
    std::cout << "圆周率: " << std::fixed << std::setprecision(2) << pi << std::endl;
    double value = 123.456;
    std::cout << "数值: " << value << std::endl;
    return 0;
}

