// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <sstream>
#include <string>
#include <iostream>

// DEBUG: Processing f-string template: Hello, {name}!
// DEBUG: F-string has 1 expressions
// DEBUG: F-string parts: 'Hello, ' + expr + '!'
// DEBUG: Generating print with 1 arguments
int main() {
    auto name = "World";
    std::cout << std::string("Hello, ") + std::string(name) + std::string("!") << std::endl;
    return 0;
}

