// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: generateCppFromPython called
// DEBUG: This should appear in the output
// DEBUG: Found 0 function definitions
// DEBUG: Found 15 module statements
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
// DEBUG: Inside print function handler
int main() {
    std::cout << "=== Testing Division ===" << std::endl;
    auto result1 = 10 / 2;
    std::cout << "10 / 2 = {result1}" << std::endl;
    auto result2 = 10 / 3;
    std::cout << "10 / 3 = {result2}" << std::endl;
    auto result3 = 15 / 4;
    std::cout << "15 / 4 = {result3}" << std::endl;
    std::cout << "
=== Testing Booleans ===" << std::endl;
    auto flag = true;
    std::cout << "True = {flag}" << std::endl;
    std::cout << "False = {False}" << std::endl;
    std::cout << "True and False = {True and False}" << std::endl;
    std::cout << "True or False = {True or False}" << std::endl;
    std::cout << "not True = {not True}" << std::endl;
    std::cout << "
=== Test Complete ===" << std::endl;
    return 0;
}

