// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: testBasicTypes
// TODO: Implement Go expression: GoBuiltinCall GoLen [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "greeting")}]
// TODO: Implement Go expression: GoBuiltinCall GoLen [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "empty")}]
void testBasicTypes() {
    std::cout << "=== Testing Basic Data Types ===" << std::endl;
    auto a = 42.0;
    auto b = 8.0;
    auto c = 16.0;
    auto d = 32.0;
    auto e = 64.0;
    auto f = 42.0;
    auto g = 8.0;
    auto h = 16.0;
    auto i = 32.0;
    auto j = 64.0;
    std::cout << "Signed integers:" << std::endl;
    std::cout << "int: %d, int8: %d, int16: %d, int32: %d, int64: %d
";
    std::cout << "Unsigned integers:" << std::endl;
    std::cout << "uint: %d, uint8: %d, uint16: %d, uint32: %d, uint64: %d
";
    auto pi = 3.14159;
    auto e_float = 2.71828;
    std::cout << "Floating point:" << std::endl;
    std::cout << "float32: %f, float64: %f
";
    auto truth = true;
    auto lie = false;
    std::cout << "Boolean:" << std::endl;
    std::cout << "true: %t, false: %t
";
    auto greeting = "Hello, World!";
    auto empty = "";
    std::cout << "String:" << std::endl;
    std::cout << "greeting: %s, empty: %s
";
    std::cout << "length: %d, empty: %d
";
    auto byteVal = 0;
    auto runeVal = 0;
    std::cout << "Byte and Rune:" << std::endl;
    std::cout << "byte: %c, rune: %c
";
}

// Generating function: testConstants
void testConstants() {
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

