// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <string>
#include <iostream>

// DEBUG: Generating print with 2 arguments
// DEBUG: Multi-argument print with 2 args
int main() {
    std::cout << " " << "x =" << 10 << std::endl;
    return 0;
}

