// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_generatePythonCall_called = 1;

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_print = 42;

int __debug_print_args = 1;

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_generatePythonCall_called = 1;

// TODO: Render other declaration types

// TODO: Render other declaration types

// TODO: Render other declaration types

int __debug_print = 42;

int __debug_print_args = 1;

// TODO: Render other declaration types

int main() {
    std::cout << "Hello, World!" << std::endl;
    auto x = 42;
    std::cout << "fstring" << std::endl;
    return 0;
}

