// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: testVariables
void testVariables() {
    auto x = 42.0;
    auto y = 3.14;
    auto s = "Hello";
    std::cout << "x = " << x << std::endl;
    std::cout << "y = " << y << std::endl;
    std::cout << "s = %s" << std::endl;
}

// Generating function: main
int main() {
    testVariables();
    std::cout << "Done!" << std::endl;
    return 0;
}

