// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

int main() {
    std::cout << "Sum: " + std::to_string(123) << std::endl;
    return 0;
}
