// Generated by HyperStatic/CXX Compiler
#include <tuple>
#include <sstream>
#include <algorithm>
#include <memory>
#include <vector>
#include <string>
#include <iostream>

// DEBUG: Starting function generation for: calculate_area

// DEBUG: Function has 1 body statements

// Processing expression: BinaryOp

// Processing binary operation: OpMul

// Processing expression: Variable

// Generated left operand: CppVar "length"

// Processing expression: Variable

// Generated right operand: CppVar "width"

// Generated binary operation result: CppBinary "*" (CppVar "length") (CppVar "width")

// DEBUG: Generated 1 C++ statements

auto calculate_area(auto length, auto width) {
    return length * width;
}

// DEBUG: Starting function generation for: main

// DEBUG: Function has 8 body statements

// Processing expression: Literal

// Processing expression: Literal

// Processing expression: BinaryOp

// Processing binary operation: OpAdd

// Processing expression: Variable

// Generated left operand: CppVar "a"

// Processing expression: Variable

// Generated right operand: CppVar "b"

// Generated binary operation result: CppBinary "+" (CppVar "a") (CppVar "b")

// Processing expression: BinaryOp

// Processing binary operation: OpMul

// Processing expression: Variable

// Generated left operand: CppVar "a"

// Processing expression: Variable

// Generated right operand: CppVar "b"

// Generated binary operation result: CppBinary "*" (CppVar "a") (CppVar "b")

// Processing expression: Call

// About to call generatePythonCall

int __debug_generatePythonCall_called = 1;

// Processing expression: Variable

// Processing expression: FString

// Processing expression: Variable

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyFString [FStringExpr {fstrExpr = Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "sum_result")}, fstrConversion = Nothing, fstrFormatSpec = Nothing}]})}

int __debug_print = 42;

int __debug_print_args = 1;

// print function called with 1 arguments

// print argument 0: CppVar "sum_result"

// Returned from generatePythonCall

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Processing expression: FString

// Processing expression: Variable

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyFString [FStringExpr {fstrExpr = Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "product")}, fstrConversion = Nothing, fstrFormatSpec = Nothing}]})}

// print function called with 1 arguments

// print argument 0: CppVar "product"

// Returned from generatePythonCall

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Processing expression: Literal

// Processing expression: Literal

// Function call: calculate_area with 2 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 6)})}

// Python argument 1: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyLiteral (PyInt 4)})}

int __debug_calculate_area = 42;

int __debug_calculate_area_args = 2;

// Regular function call: calculate_area

int __debug_calculate_area_result = 1;

// Returned from generatePythonCall

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Processing expression: FString

// Processing expression: Variable

// Function call: print with 1 args

// Python argument 0: Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = ArgPositional (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyFString [FStringExpr {fstrExpr = Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "area")}, fstrConversion = Nothing, fstrFormatSpec = Nothing}]})}

// print function called with 1 arguments

// print argument 0: CppVar "area"

// Returned from generatePythonCall

// DEBUG: Generated 8 C++ statements

int main() {
    auto a = 10;
    auto b = 5;
    auto sum_result = a + b;
    auto product = a * b;
    std::cout << sum_result << std::endl;
    std::cout << product << std::endl;
    auto area = calculate_area(6, 4);
    std::cout << area << std::endl;
    return 0;
}

// Processing expression: Comparison

// Processing expression: Variable

// Processing expression: Literal

// Processing expression: Call

// About to call generatePythonCall

// Processing expression: Variable

// Function call: main with 0 args

int __debug_main = 42;

int __debug_main_args = 0;

// Regular function call: main

int __debug_main_result = 1;

// Returned from generatePythonCall

