// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

// TODO: Implement Python expression: PyBoolOp OpAnd [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "p")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "q")}]
// TODO: Implement Python expression: PyBoolOp OpOr [Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "p")},Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "q")}]
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "p")})
// TODO: Implement Python expression: PyUnaryOp OpNot (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = PyVar (Identifier "q")})
int main() {
    auto a = 10;
    auto b = 3;
    std::cout << a + b << std::endl;
    std::cout << a - b << std::endl;
    std::cout << a * b << std::endl;
    std::cout << a / b << std::endl;
    std::cout << a + b << std::endl;
    std::cout << a % b << std::endl;
    std::cout << a + b << std::endl;
    auto x = 5;
    auto y = 10;
    std::cout << x == y << std::endl;
    std::cout << x != y << std::endl;
    std::cout << x > y << std::endl;
    std::cout << x < y << std::endl;
    std::cout << x >= y << std::endl;
    std::cout << x <= y << std::endl;
    auto p = true;
    auto q = false;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    std::cout << 0 << std::endl;
    return 0;
}

