// Generated by HyperStatic/CXX Compiler
#include <vector>
#include <string>
#include <iostream>

int main() {
    auto my_list = std::vector<int>{1, 2, 3};
    std::cout << my_list << std::endl;
    return 0;
}

