// Generated by Fluxus C++ Compiler
#include <stdexcept>
#include <cstddef>
#include <optional>
#include <vector>
#include <sstream>
#include <string>
#include <iostream>

std::string word = "fluxus";

auto chunk;

std::string py_bool_to_string(bool value)
{
  if (value)
  {
    return "True";
  }
  else
  {
    return "False";
  }
}

std::string py_float_to_string(double value)
{
  std::ostringstream oss;
  (oss << value);
  std::string result = oss.str();
  if (((result.find(".") == std::string::npos) && ((result.find("e") == std::string::npos) && (result.find("E") == std::string::npos))))
  {
    result.append(".0");
  }
  return result;
}

std::vector<long long> range(long long n)
{
  std::vector<long long> result;
  result.reserve(n);
  for (long long i = 0; (i < n); ++i)
  {
    result.push_back(i);
  }
  return result;
}

void fluxus_runtime_abort(const char* message)
{
  throw std::runtime_error(message);
}

template <typename typename Seq>
Seq fluxus_slice(const Seq& seq, std::optional<long long> start, std::optional<long long> stop, std::optional<long long> step)
{
  long long size_ = (long long)seq.size();
  long long step_ = (step.has_value() ? (long long)step.value() : 1);
  if ((step_ == 0))
  {
    fluxus_runtime_abort("Python slice step cannot be zero");
    return seq;
  }
  bool forward_ = (step_ > 0);
  long long start_ = (start.has_value() ? (long long)start.value() : (forward_ ? 0 : (size_ - 1)));
  if ((start_ < 0))
  {
    (start_ += size_);
  }
  if (forward_)
  {
    if ((start_ < 0))
    {
      (start_ = 0);
    }
    if ((start_ > size_))
    {
      (start_ = size_);
    }
  }
  else
  {
    if ((start_ < -1))
    {
      (start_ = -1);
    }
    if ((start_ >= size_))
    {
      (start_ = (size_ - 1));
    }
  }
  long long stop_ = (stop.has_value() ? (long long)stop.value() : (forward_ ? size_ : -1));
  if ((stop_ < 0))
  {
    (stop_ += size_);
  }
  if (forward_)
  {
    if ((stop_ < 0))
    {
      (stop_ = 0);
    }
    if ((stop_ > size_))
    {
      (stop_ = size_);
    }
  }
  else
  {
    if ((stop_ < -1))
    {
      (stop_ = -1);
    }
    if ((stop_ >= size_))
    {
      (stop_ = (size_ - 1));
    }
  }
  Seq result_ = Seq{};
  if (forward_)
  {
    for (long long idx_ = start_; (idx_ < stop_); (idx_ += step_))
    {
      if (((idx_ < 0) || (idx_ >= size_)))
      {
        break;
      }
      result_.push_back(seq[(std::size_t)idx_]);
    }
  }
  else
  {
    for (long long idx_ = start_; (idx_ > stop_); (idx_ += step_))
    {
      if (((idx_ < 0) || (idx_ >= size_)))
      {
        break;
      }
      result_.push_back(seq[(std::size_t)idx_]);
    }
  }
  return result_;
}

int main()
{
  const std::string __name__ = "__main__";
  (chunk = fluxus_slice(word, std::optional<long long>{(long long)0}, std::optional<long long>{(long long)3}, std::optional<long long>{}));
  ((std::cout << chunk) << std::endl);
  return 0;
}