// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>

int main() {
    int result = 0;
    int i = 0;
    while (i < 1000000) {
    result = result + i % 1000;
    i = i + 1;

}
    std::cout << "Processed " << result << " elements" << std::endl;;
    return 0;
}

