// Generated by HyperStatic/CXX Compiler
/* Original Source (test/python-tests/feature_fstring.py):
# F-string tests
name = "Alice"
age = 30
temperature = 23.5

# Basic f-string
message = f"Hello, {name}!"
print(message)

# F-string with expressions
info = f"{name} is {age} years old."
print(info)

# F-string with calculations
birth_year = 2024 - age
year_message = f"{name} was born around {birth_year}."
print(year_message)

# F-string with format specification
temp_message = f"The temperature is {temperature:.1f}°C"
print(temp_message)
*/

// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>

int main() {
    int result = 0;
    int i = 0;
    while (i < 1000000) {
    result = result + i % 1000;
    i = i + 1;

}
    std::cout << "14" << std::endl;;
    return 0;
}


// Generated by HyperStatic/CXX Compiler
/* Original Source (test/python-tests/basic_arithmetic.py):
# Basic arithmetic operations
x = 10
y = 20
sum_result = x + y
diff = y - x
product = x * y
quotient = y // x
remainder = y % x

print("Sum: " + str(sum_result))
print("Difference: " + str(diff))
print("Product: " + str(product))
print("Quotient: " + str(quotient))
print("Remainder: " + str(remainder))
*/

// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>


