// Generated by HyperStatic/CXX Compiler
#include <string>
#include <iostream>

int main() {
    auto name = "Alice";
    auto age = 30;
    auto temperature = 23.5;
    auto message = "Hello, {name}!";
    std::cout << message << std::endl;
    auto info = "{name} is {age} years old.";
    std::cout << info << std::endl;
    auto birth_year = 2024 - age;
    auto year_message = "{name} was born around {birth_year}.";
    std::cout << year_message << std::endl;
    auto temp_message = "The temperature is {temperature:.1f}°C";
    std::cout << temp_message << std::endl;
    return 0;
}

