// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>
#include <vector>
#include <optional>
#include <unordered_map>
#include <tuple>
#include <cstdio>
#include <queue>

class LargeStruct {
    // TODO: Render class members and methods
};

void testEscapeAnalysis() {
    return;
}

int* heapAllocation() {
    return nullptr;
}

int stackAllocation() {
    return 0;
}

void testValueVsPointer() {
    return;
}

void passByPointer(LargeStruct* s) {
    return;
}

void passByValue(LargeStruct s) {
    return;
}

