// Generated by HyperStatic/CXX Compiler
#include <iostream>
#include <string>
#include <vector>
#include <optional>
#include <unordered_map>
#include <tuple>
#include <cstdio>
#include <queue>

class Address {
    // TODO: Render class members and methods
};

class Person {
    // TODO: Render class members and methods
};

