// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
// TODO: Render other declaration types

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: fibonacci
int fibonacci(int n) {
    if (n <= 1.0) {
    {
    return n;
}
}
    return fibonacci(n - 1.0) + fibonacci(n - 2.0);
}

// Generating function: concurrentFibonacci
void concurrentFibonacci(int n, Channel ch) {
    auto result = fibonacci(n);
    ch.send(result);
}

// Generating fallback main function - Go parser not working properly
int main() {
    return 0;
}

