// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 2 declarations
// Generating function: fibonacci
// DEBUG: goForCond found: Located {locSpan = SourceSpan {spanFilename = "<no-file>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoComparison OpLe (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "i")}) (Located {locSpan = SourceSpan {spanFilename = "<input>", spanStart = SourcePos {posLine = 0, posColumn = 0}, spanEnd = SourcePos {posLine = 0, posColumn = 0}}, locValue = GoIdent (Identifier "n")})}
auto fibonacci(auto n) {
    if (n <= 1.0) {
    {
    return n;
}
}
    double a = 0.0;
    double b = 1.0;
    for (double i = 2.0; i <= n; ++i) {
    auto c = a + b;
    a = b;
    b = c;
}
    return b;
}

// Generating function: main
int main() {
    std::cout << "fib(5) = " << fibonacci(5.0) << std::endl;
    std::cout << "fib(6) = " << fibonacci(6.0) << std::endl;
    std::cout << "fib(7) = " << fibonacci(7.0) << std::endl;
    return 0;
}

