// Generated by HyperStatic/CXX Compiler - DEBUG VERSION
#include <iomanip>
#include <chrono>
#include <atomic>
#include <functional>
#include <vector>
#include <queue>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <string>
#include <iostream>

// Generating C++ for Go package: main
template<typename T>
class Channel {
    std::queue<T> queue_;

    std::mutex mutex_;

    std::condition_variable cv_;

    size_t capacity_;

    Channel(size_t capacity) {
        this->capacity_ = capacity;
    }

    void send(T value) {
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return this->queue_.size() < this->capacity_;
});
        this->queue_.push(value);
        cv_.notify_one();
    }

    T receive() {
        T value;
        std::unique_lock<std::mutex> lock = std::unique_lock<std::mutex>(this->mutex_);
        this->cv_.wait(lock, [this]() {
    return !this->queue_.empty();
});
        value = this->queue_.front();
        this->queue_.pop();
        cv_.notify_one();
        return value;
    }

};

// Found 1 files in package
// Processing Go file with 1 declarations
// Generating function: main
int main() {
    std::cout << "Simple Calculator" << std::endl;
    double a = 10.0;
    double b = 5.0;
    auto sum = a + b;
    auto diff = a - b;
    auto prod = a * b;
    auto quot = a / b;
    auto mod = a % b;
    std::cout << "a = %d, b = %d
";
    std::cout << "Addition: %d + %d = %d
";
    std::cout << "Subtraction: %d - %d = %d
";
    std::cout << "Multiplication: %d * %d = %d
";
    std::cout << "Division: %d / %d = %d
";
    std::cout << "Modulus: %d %% %d = %d
";
    double x = 3.14;
    double y = 2.71;
    std::cout << "Float operations:" << std::endl;
    std::cout << "%.2f + %.2f = %.2f
";
    std::cout << "%.2f * %.2f = %.2f
";
    return 0;
}

