name: Stack Test

on:
  push:
  pull_request:

jobs:
  stack-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest

      - name: Cache Stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'fluxus.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Run stack test
        run: stack test --no-terminal
